### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by klppl** [imagegenius/docker-ai-chat-app#1]
I get this error

docker: Error response from daemon: Head "https://ghcr.io/v2/imagegenius/ai-chat-app/manifests/latest": denied.

**Comment by hydazz** [comment]
how did you find this repo? I just published it haha. The package has just been set to public, you should now have access to pull `ghcr.io/imagegenius/ai-chat-app`

**Comment by klppl** [comment]
It just popped up in my unraid apps section :)

![image](https://user-images.githubusercontent.com/2523049/222950118-5d551a41-5603-47b2-97f0-71658c3253dc.png)

**Comment by klppl** [comment]
It's now up and running. Thanks :)

![image](https://user-images.githubusercontent.com/2523049/222950307-3a6af43c-d931-473c-a303-d09df6ca7eb6.png)

**Comment by klppl** [comment]
Works after package set to public.
