### ISSUE TITLE
Add 'sharp' package

### ISSUE THREAD

**Issue by specked** [imagegenius/docker-ai-chat-app#10]
"For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization."

I added it by: `/usr/lib/node_modules/corepack/shims/yarn add sharp`

**Comment by hydazz** [comment]
What image optimisation is there to do?

**Comment by specked** [comment]
no idea but I get an error when I submit a chat and the error message is different after installing 'sharp'.

**Comment by hydazz** [comment]
> different

What does the error change to?

**Comment by specked** [comment]
it goes from this: 
![image](https://user-images.githubusercontent.com/1870392/223434263-19e6694e-03bf-43e2-9143-99373ea13cda.png)

to

![image](https://user-images.githubusercontent.com/1870392/223434789-e351985e-e0dc-4945-ab37-14fe098c5e90.png)

**Comment by specked** [comment]
I guess they're both 500 errors so same error just looks different? The original message to add sharp was provided in the docker log

**Comment by hydazz** [comment]
i will add sharp soon
