### ISSUE TITLE
[Request] Hide the settings page for non-admins/require auth?

### ISSUE THREAD

**Issue by HotWinterDays** [imagegenius/docker-ai-chat-app#11]
Hey thanks for the great Docker container. It's really easy to get going and does the thing. Just wanted to ask since I am not much of a dev, is there a way to hide the settings page/make it so a user has to be authenticated to see it?

Are there any plans for user management/differentiation?

I want to share it with folks but don't want everyone's chats to be cluttered together and for anyone to be able to edit the settings.

**Comment by hydazz** [comment]
this is just a docker image for https://github.com/bitswired/ai-chat-app, share this there :)
