### ISSUE TITLE
Get this

### ISSUE THREAD

**Issue by Nanorulez123** [imagegenius/docker-ai-chat-app#16]
The column `main.Setting.userId` does not exist in the current database.
prisma:error 
Invalid `prisma.setting.findMany()` invocation:

The column `main.Setting.userId` does not exist in the current database.
cprisma:error 
Invalid `prisma.setting.findMany()` invocation:

The column `main.Setting.userId` does not exist in the current database.

**Comment by hydazz** [comment]
do you have any more information...? host os? docker-compose or docker? docker CLI command? unraid template?

**Comment by T1Software** [comment]
Same for me. Using the Unraid Template.

**Comment by Nanorulez123** [comment]
Unraid template , default , behaviour is it spams that error once logged in As you try to enter an API key.Is there anything to do once the template is ran.  ---- On Mon, 20 Mar 2023 03:13:03 +0000  ***@***.******@***.***> wrote ----  
do you have any more information...? host os? docker-compose or docker? docker CLI command? unraid template?

**Comment by hydazz** [comment]
I just did a fresh install and it seems to be working for me, can you provide the variables you are using in the template?

**Comment by Nanorulez123** [comment]
Fresh install here too, default template, Latest unraidVariables when i hit install aredocker run  -d  --name='ai-chat-app'  --net='bridge'  -e TZ="Europe/London"  -e HOST_OS="Unraid"  -e HOST_HOSTNAME="PonTower"  -e HOST_CONTAINERNAME="ai-chat-app"  -e 'NEXTAUTH_SECRET'='secret'  -e 'NEXTAUTH_URL'='http://UNRAID ip here:3000'  -e ***@***.***'  -e 'ADMIN_PASSWORD'='password'  -e 'PUID'='99'  -e 'PGID'='100'  -e 'UMASK'='022'  -l net.unraid.docker.managed=dockerman  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/ai-chat-app.png'  -p '3000:3000/tcp'  -v '/mnt/user/appdata/ai-chat-app':'/config':'rw' 'ghcr.io/imagegenius/ai-chat-app' 7751a03064d4a68a05cb7bef70b7ba35a65388ee5fd78b1d76a8216969af39a0  ---- On Mon, 20 Mar 2023 11:19:26 +0000  ***@***.******@***.***> wrote ----  
I just did a fresh install and it seems to be working for me, can you provide the variables you are using in the template?

**Comment by hydazz** [comment]
try deleting `/mnt/user/appdata/ai-chat-app`?

**Comment by Nanorulez123** [comment]
That worked, apologies for such a simple fix, still may be worth if possible to have new installs clear that on install?  ---- On Mon, 20 Mar 2023 11:31:38 +0000  ***@***.******@***.***> wrote ----  
try deleting /mnt/user/appdata/ai-chat-app?

**Comment by hydazz** [comment]
this is a new app, there are going to be bugs, and migration issues when they push a new commit

**Comment by osnapitsjoey** [comment]
i've done all of this and still dont have it working. I have no idea what is going wrong with my machine. could it be unraid trail??
