### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by socalit** [imagegenius/docker-ai-chat-app#19]
Can't save the API key after the update.

GET http://0.0.0.0:3000/api/trpc/settings.getSettings?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 500 (Internal Server Error)

**Comment by hydazz** [comment]
What are your env variables?

**Comment by socalit** [comment]
prisma.setting.upsert. The column `userId` does not exist in the current database. I'll jump over to that thread. Thanks.

**Comment by socalit** [comment]
Found the solution to my problem. I need to add the db. Add the following in unraid:
Config Type: Variable
Name: DATABASE_URL 
Key: DATABASE_URL
Value: file:./db.sqlite \

**Comment by hydazz** [comment]
that variable is specified in the dockerfile `ENV DATABASE_URL="file:/config/db.sqlite"`, It should not be needed, it also should be `file:/config/db.sqlite`, `file:./db.sqlite` has the database saved in a directory that is not persistent

can you try remove the variable you have specified in the template, open a terminal into the container and run `printenv` and paste the output here

**Comment by socalit** [comment]
Oh, you're right. It's in there. The path?

DATABASE_URL=file:/config/db.sqlite
PUID=99
CHARSET=UTF-8
HOSTNAME=xxx
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
HOST_CONTAINERNAME=ai-chat-app
NEXTAUTH_URL=http://xxx.xxx.xxx.xxx:3000
UMASK=022
PWD=/
NODE_ENV=production
TZ=America/Los_Angeles
ADMIN_EMAIL=xxxxx@xxxx
HOME=/root
LANG=C.UTF-8
PGID=100
ADMIN_PASSWORD=xxxxxxxx
S6_VERBOSITY=1
S6_STAGE2_HOOK=/docker-mods
NEXTAUTH_SECRET=xxxxx
TERM=xterm
HOST_OS=Unraid
SHLVL=1
PS1=$(whoami)@$(hostname):$(pwd)\$ 
LC_COLLATE=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOST_HOSTNAME=xxxx
_=/bin/printenv

**Comment by socalit** [comment]
I removed the old db.sqlite and reinstalled it. Looks like is working now. Thanks for the help.
