### ISSUE TITLE
The table `main.Chat` does not exist in the current database. prisma:error 

### ISSUE THREAD

**Issue by juliors** [imagegenius/docker-ai-chat-app#2]
After start the container and visit http://x.x.x.x:3000/chat I get the following error:

The table `main.Chat` does not exist in the current database.
prisma:error 
Invalid `prisma.chat.findMany()` invocation:

Browser show: 404 This page could not be found.

**Comment by hydazz** [comment]
Update the container, if it continues occurring delete the db file in the config

**Comment by juliors** [comment]
After force update the container and delete db file, works properly.
