### ISSUE TITLE
Unraid - Port already in use.

### ISSUE THREAD

**Issue by ramirezrick** [imagegenius/docker-ai-chat-app#25]
Hello everyone.  Port 3000 is already in use, and no matter what I try, I can't get it to work. The logs always shows **ready started server on 0.0.0.0:3000, url: http://localhost:3000** regardless of the port I use on the PATHs

**Comment by hydazz** [comment]
do you have `Network Type` set to `Bridge` and the `WebUI` entry set to something else?

**Comment by ramirezrick** [comment]
> do you have `Network Type` set to `Bridge` and the `WebUI` entry set to something else?

Yes. Here's a screenshot - https://i.imgur.com/PQVSx0D.png

**Comment by hydazz** [comment]
the `container port` needs to be set to `3000` - along with the webui port `http://[IP]:[PORT:3000]`

You need to map port `3000` from within the container to an unused port on the host, if port `3001` is unused, this should be fine.

**Comment by ramirezrick** [comment]
> map port `3000` from within the container to an unused port

That did the trick. Here's a screenshot of the new settings in case anyone else is experiencing the same problem.

https://i.imgur.com/y4nzHT0.png

Thank you for your help **@hydazz**
