### ISSUE TITLE
Run docker in UNraid environment. The first time you visit the WEBUI-setting log, the error message is as follows, the setting file cannot be saved, and it cannot run effectively.

### ISSUE THREAD

**Issue by zrwd01** [imagegenius/docker-ai-chat-app#4]
Run docker in UNraid environment. The first time you visit the WEBUI-setting log, the error message is as follows, the setting file cannot be saved, and it cannot run effectively.
============================================================

prisma:error 
Invalid `prisma.chat.findMany()` invocation:

The table `main.Chat` does not exist in the current database.
prisma:error 
Invalid `prisma.chat.findMany()` invocation:

The table `main.Chat` does not exist in the current database.
prisma:error 
Invalid `prisma.chat.findMany()` invocation:

The table `main.Chat` does not exist in the current database.
prisma:error 
Invalid `prisma.setting.findMany()` invocation:

The table `main.Setting` does not exist in the current database.
prisma:error 
Invalid `prisma.setting.findMany()` invocation:

The table `main.Setting` does not exist in the current database.
prisma:error 
Invalid `prisma.setting.findMany()` invocation:

The table `main.Setting` does not exist in the current database.
prisma:error 
Invalid `prisma.setting.findMany()` invocation:

The table `main.Setting` does not exist in the current database.

**Comment by hydazz** [comment]
Looks to be the same as https://github.com/imagegenius/docker-ai-chat-app/issues/2, check for updates, is there one available?

**Comment by zrwd01** [comment]
yes, it worked, after I del all the files under the config directory and forced to update, thanks
