### ISSUE TITLE
API key doesn't appear to be saving

### ISSUE THREAD

**Issue by wyliebutler** [imagegenius/docker-ai-chat-app#5]
API key doesn't appear to be saving . . . as a result the I cannot add to the chat window

**Comment by hydazz** [comment]
Is there an update available?, try force update

**Comment by wyliebutler** [comment]
I just did the install using the UNRAID community app.  Should that be the latest?

**Comment by hydazz** [comment]
That will install the latest version available at the time, is there anything in the logs?

**Comment by specked** [comment]
Same issue here. Nothing in the logs:

`╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  To support this applications developer(s) visit:
  Obico: https://www.obico.io/docs/developer-guides/contribute/#buy-us-a-coffee
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 99
  User GID: 100
╚═══════════════════════════════╝
[custom-init] No custom files found, skipping...
[ig-init] done.

> chat-app@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000`

**Comment by wyliebutler** [comment]
Here's my log . . . nothing seems off.
╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  To support this applications developer(s) visit:
  Obico: https://www.obico.io/docs/developer-guides/contribute/#buy-us-a-coffee
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 99
  User GID: 100
╚═══════════════════════════════╝
[custom-init] No custom files found, skipping...
[ig-init] done.

> chat-app@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000

**Comment by herc5854** [comment]
I am having the same issue has anyone gotten it to work yet on unraid.

**Comment by hydazz** [comment]
Saving the API key works for me with a fresh install?

**Comment by klppl** [comment]
Yes it works for me. Just save the api key a second time in gui

**Comment by wyliebutler** [comment]
I reinstalled a couple of times,  No Luck :-(

**Comment by herc5854** [comment]
Me too


Sent from Yahoo Mail for iPhone


On Sunday, March 5, 2023, 6:33 PM, wyliebutler ***@***.***> wrote:




I reinstalled a couple of times, No Luck :-(

**Comment by hydazz** [comment]
@wyliebutler does anything appear in the logs after attempting to save the key?

**Comment by wyliebutler** [comment]
The log remains the same.  No new entries

**Comment by klppl** [comment]
This is my Unraid + settings. After starting the container you need to enter the same API key again, press Save. It maybe looks like it doesn't work or save. Restart the container. 

Tried this on two difference Unraid servers.

![image](https://user-images.githubusercontent.com/2523049/223396286-a9fca9de-e391-40f8-80ee-85f8026e6747.png)


![image](https://user-images.githubusercontent.com/2523049/223396341-f5e86618-494d-4dfc-a5a7-633db16d86ac.png)

**Comment by hydazz** [comment]
The api key variable did not seem to do anything yet

**Comment by wyliebutler** [comment]
I can now bring up a chat window... but it never returns any results.   hmmm

**Comment by i-kakc** [comment]
> This is my Unraid + settings. After starting the container you need to enter the same API key again, press Save. It maybe looks like it doesn't work or save. Restart the container.
> 
> Tried this on two difference Unraid servers.
> 
> ![image](https://user-images.githubusercontent.com/2523049/223396286-a9fca9de-e391-40f8-80ee-85f8026e6747.png)
> 
> ![image](https://user-images.githubusercontent.com/2523049/223396341-f5e86618-494d-4dfc-a5a7-633db16d86ac.png)

Thanks,it's helpful for add variable "OPENAI_API_KEY"

**Comment by MalMcWil** [comment]
I'm having the same issue on Unraid as well. i tried adding the OPENAI_API_KEY as a variable, but when i try and chat, nothing happens. When i go to import a template, nothing happens there, either.

**Comment by herc5854** [comment]
My API key is now saved, I can grab some templates but they do not work I click on them and nothing. I start a chat that works but nothing happens when I type in the chat box. Not sure if others have this same issue or if anyone knows of something I could do to get it to work.

**Comment by lb1blink** [comment]
> My API key is now saved, I can grab some templates but they do not work I click on them and nothing. I start a chat that works but nothing happens when I type in the chat box. Not sure if others have this same issue or if anyone knows of something I could do to get it to work.

Yep, same issue on UnRAID. Not working.

**Comment by hydazz** [comment]
probably an upstream issue: https://github.com/bitswired/ai-chat-app/issues, not much I can do, the image works fine
