### ISSUE TITLE
Nothing displayed on "chats" page

### ISSUE THREAD

**Issue by specked** [imagegenius/docker-ai-chat-app#6]
API key has been saved but no interface is shown on /chats

![image](https://user-images.githubusercontent.com/1870392/222989930-cdceac11-d60b-403d-b1ad-733c697479b0.png)

```
 << mutation #6 chat.seedChatFromTemplate  
Object { input: {…}, result: TRPCClientError, elapsedMs: 222, context: {} }
_app-35515c0ed56997bb.js:5:346
    NextJS 6
        w
        l
        error
        error
        error
        links
```

**Comment by hydazz** [comment]
upstream issue: https://github.com/bitswired/ai-chat-app
