### ISSUE TITLE
Chats not loading

### ISSUE THREAD

**Issue by dhuesca** [imagegenius/docker-ai-chat-app#7]
Running on unRAID 6.11.5, I managed to save the API key, but Chats are not loading
<img width="800" alt="1" src="https://user-images.githubusercontent.com/9075814/223052186-51e3df18-ae42-437a-b954-7b47af512ead.PNG">

The only way to start a chat is by using a template

**Comment by hydazz** [comment]
upstream issue: https://github.com/bitswired/ai-chat-app
