### ISSUE TITLE
Main Chat button links to wrong page

### ISSUE THREAD

**Issue by dhuesca** [imagegenius/docker-ai-chat-app#8]
"start" button links to "/chat" instead of "/chats" and it causes a 404

<img width="800" alt="3" src="https://user-images.githubusercontent.com/9075814/223052629-2bdad7b5-d437-4b69-b892-90e7f4529880.PNG">

**Comment by hydazz** [comment]
upstream issue: https://github.com/bitswired/ai-chat-app
